### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by artelse** [FrostyX/dired-open-with#3]
Just a question, when I right click a file, I get the normal contextual menu with the Open with.. item. This is ok with me, but in the screenshot you show a dialog box with additional info on the possible applications.

**Comment by FrostyX** [comment]
> when I right click a file, I get the normal contextual menu with the Open with.. item

Do you mean in Dired or GUI file managers like Nautilis or Dolphin?

> in the screenshot you show a dialog box with additional info on the possible applications.

The screenshot shows `M-x dired-open-with` on some file in Dired. It looks like a dialog because I used [vertico-posframe](https://github.com/tumashu/vertico-posframe) to have a concise image for README and social media. More realistically it looks like this:

![Screenshot_2024-06-04_11-25-51](https://github.com/FrostyX/dired-open-with/assets/2151771/eb474b91-4537-4496-97ae-ccf8cb5fa0f7)

Not sure if this answers your question.

**Comment by artelse** [comment]
Ah, just because I used the right click contextual menu on the dired buffer. When using `M-x dired-open-with` it opens the options in the minibuffer as shown above. Thanks for the package, is very useful!

**Comment by FrostyX** [comment]
I am glad it helped :-)
